Vagrant.configure(2) do |config|

  # CentOS 6
  config.vm.define "el6" do |el6|
    el6.vm.box = "geerlingguy/centos6"
    el6.vm.hostname = "curator-el6"
    el6.vm.provider :virtualbox do |virtualbox|
      virtualbox.memory = 2048
    end
  end

  # CentOS 7
  config.vm.define "el7" do |el7|
    el7.vm.box = "geerlingguy/centos7"
    el7.vm.hostname = "curator-el7"
  end

  # Ubuntu 14.04
  config.vm.define "ub14" do |ub14|
    ub14.vm.box = "geerlingguy/ubuntu1404"
    ub14.vm.hostname = "curator-ub14"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
    # ansible.extra_vars = { es_update_plugins: "True" }
  end

end
